close connection
DSCLAB/HDS-DCFS-Docker pull request #31
Opened 2022-08-11 08:37 UTC by chungen0126

@steinsgateted close connection

2022-08-11 08:49 UTC, CW-B-W commented on dcfs/dcfs-share/dcfs-run/demo.py
> +                db_engine.connect().close()
Hello @chungen0126,
I don't really get this.

In this line, do you mean to initiate a new connection to the DBMS, and then close the connection immediately?

ref:
https://docs.sqlalchemy.org/en/13/core/connections.html#sqlalchemy.engine.Engine.connect

2022-08-11 08:52 UTC, CW-B-W commented on dcfs/dcfs-share/dcfs-run/demo.py
> +                db_engine.connect().close()
I think only 
```suggestion
                db_engine.dispose()
```
is needed?

ref: https://stackoverflow.com/a/47964066/16113175

2022-08-15 07:45 UTC, CW-B-W commented on web/flask/hello.py
>      return sorted(db.list_collection_names())
Hello @chungen0126 ,
Does
```python
return sorted(db.list_collection_names())
```
work when we have done
```python
mongo_client.close()
```
?

2022-08-15 08:36 UTC, steinsgateted requested changes

2022-08-15 08:36 UTC, steinsgateted commented on web/flask/hello.py
>      cursor.execute("DROP TABLE {}".format(table_name))
same meaning as 252 and 253

2022-08-15 08:48 UTC, steinsgateted commented on web/flask/requirements.txt
> +protobuf==3.20.0
prevent forgetting:
Fixed the protobuf version because the flask web page was not opened

2022-08-15 08:59 UTC, CW-B-W commented on web/flask/requirements.txt
> +protobuf==3.20.0
Hello @steinsgateted ,
What happens if we don't specify the `protobuf==3.20.0` version?
(just out of curiosity)

2022-08-15 09:21 UTC, chungen0126 commented on web/flask/requirements.txt
> +protobuf==3.20.0
> What happens if we don't specify the protobuf==3.20.0 version?

flask  will crash.

2022-08-15 09:28 UTC, CW-B-W commented on web/flask/requirements.txt
> +protobuf==3.20.0
Why?

2022-08-15 09:40 UTC, steinsgateted commented on web/flask/requirements.txt
> +protobuf==3.20.0
I have no idea.

2022-08-15 09:44 UTC, steinsgateted approved these changes
+1 Thanks.

2022-08-15 09:46 UTC, chungen0126 commented on web/flask/requirements.txt
> +protobuf==3.20.0
There must be some Compatibility issues, I think specify the protobuf version is more stable.

2022-08-15 09:47 UTC, CW-B-W commented on web/flask/requirements.txt
> +protobuf==3.20.0
Thanks

2022-08-15 09:49 UTC, merged